### ISSUE TITLE
Idea: Remove starting keys

### ISSUE THREAD

**Issue by jdonland** [HomebrewHomunculus/BrogueCE#22]
I like the simplification of keys being interchangeable and stacking in the inventory, but starting with two of them somewhat trivializes key machines and especially vaults with a key as a possible reward.

**Comment by HomebrewHomunculus** [comment]
I think I'd tend to agree. Overall I'm not happy with the changes I made to the keys, nor the scoring changes which I haven't been able to push to the finish. I might roll back the "free starting keys" just to bring it one step closer to mainline Brogue CE and see how it feels.

**Comment by HomebrewHomunculus** [comment]
Both the interchangeable (fungible) keys and the starting keys have been removed while resolving conflicts with upstream BrogueCE v1.13:
https://github.com/HomebrewHomunculus/BrogueCE/pull/27/commits/55c7356288c7e8a9314e04a80e8def548fba269e

**Comment by HomebrewHomunculus** [comment]
Since the v1.13 with removal of the free keys was merged, I'll close this issue as obsolete - even though it also removed the keys, which isn't quite what you asked for. But we'll try to get a functional v1.13 release out and then see if we still miss the stackable keys.
